/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_inxas_rit_widget_mediator_windows_WinWindowMediator */

#ifndef _Included_net_inxas_rit_widget_mediator_windows_WinWindowMediator
#define _Included_net_inxas_rit_widget_mediator_windows_WinWindowMediator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_create
  (JNIEnv *, jobject);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    setAlwaysOnTop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_setAlwaysOnTop
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    setBounds
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_setBounds
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    setClientBounds
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_setClientBounds
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    setTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_setTitle
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_setVisible
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    toBack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_toBack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    toFront
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_toFront
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    nextMessage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_nextMessage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_inxas_rit_widget_mediator_windows_WinWindowMediator
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_inxas_rit_widget_mediator_windows_WinWindowMediator_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
